insert into country
  (name_country,currencies,languages,flag,continents) 
values
  ('Afghanistan','Afghan afghani','Dari','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png','Asia'),
  ('Germany','Euro','German','https://flagcdn.com/w320/de.png','Europe'),
  ('Mayotte','Euro','French','https://flagcdn.com/w320/yt.png','Africa'),
  ('Marshall Islands','United States dollar','English','https://flagcdn.com/w320/mh.png','Oceania'),
  ('Sudan','Sudanese pound','Arabic','https://flagcdn.com/w320/sd.png','Africa'),
  ('Tanzania','Tanzanian shilling','English','https://flagcdn.com/w320/tz.png','Africa'),
  ('Poland','Polish złoty','Polish','https://flagcdn.com/w320/pl.png','Europe'),
  ('Macau','Macanese pataca','Portuguese','https://flagcdn.com/w320/mo.png','Asia'),
  ('Timor-Leste','United States dollar','Portuguese','https://flagcdn.com/w320/tl.png','Oceania'),
  ('Togo','West African CFA franc','French','https://flagcdn.com/w320/tg.png','Africa'),
  ('Czechia','Czech koruna','Czech','https://flagcdn.com/w320/cz.png','Europe'),
  ('Bulgaria','Bulgarian lev','Bulgarian','https://flagcdn.com/w320/bg.png','Europe'),
  ('Monaco','Euro','French','https://flagcdn.com/w320/mc.png','Europe'),
  ('Uganda','Ugandan shilling','English','https://flagcdn.com/w320/ug.png','Africa'),
  ('Trinidad and Tobago','Trinidad and Tobago dollar','English','https://flagcdn.com/w320/tt.png','North America'),
  ('Algeria','Algerian dinar','Arabic','https://flagcdn.com/w320/dz.png','Africa'),
  ('Estonia','Euro','Estonian','https://flagcdn.com/w320/ee.png','Europe'),
  ('Ukraine','Ukrainian hryvnia','Ukrainian','https://flagcdn.com/w320/ua.png','Europe'),
  ('Mauritania','Mauritanian ouguiya','Arabic','https://flagcdn.com/w320/mr.png','Africa'),
  ('Georgia','lari','Georgian','https://flagcdn.com/w320/ge.png','Asia'),
  ('Sint Maarten','Netherlands Antillean guilder','English','https://flagcdn.com/w320/sx.png','North America'),
  ('Namibia','Namibian dollar','Afrikaans','https://flagcdn.com/w320/na.png','Africa'),
  ('North Macedonia','denar','Macedonian','https://flagcdn.com/w320/mk.png','Europe'),
  ('Mauritius','Mauritian rupee','English','https://flagcdn.com/w320/mu.png','Africa'),
  ('Kiribati','Australian dollar','English','https://flagcdn.com/w320/ki.png','Oceania'),
  ('Greece','Euro','Greek','https://flagcdn.com/w320/gr.png','Europe'),
  ('Republic of the Congo','Central African CFA franc','French','https://flagcdn.com/w320/cg.png','Africa'),
  ('Equatorial Guinea','Central African CFA franc','French','https://flagcdn.com/w320/gq.png','Africa'),
  ('Niue','New Zealand dollar','English','https://flagcdn.com/w320/nu.png','Oceania'),
  ('British Indian Ocean Territory','United States dollar','English','https://flagcdn.com/w320/io.png','Asia'),
  ('Kosovo','Euro','Albanian','https://flagcdn.com/w320/xk.png','Europe'),
  ('Palau','United States dollar','English','https://flagcdn.com/w320/pw.png','Oceania'),
  ('Qatar','Qatari riyal','Arabic','https://flagcdn.com/w320/qa.png','Asia'),
  ('United States','United States dollar','English','https://flagcdn.com/w320/us.png','North America'),
  ('Cayman Islands','Cayman Islands dollar','English','https://flagcdn.com/w320/ky.png','North America'),
  ('Botswana','Botswana pula','English','https://flagcdn.com/w320/bw.png','Africa'),
  ('Palestine','Egyptian pound','Arabic','https://flagcdn.com/w320/ps.png','Asia'),
  ('South Africa','South African rand','Afrikaans','https://flagcdn.com/w320/za.png','Africa'),
  ('Vietnam','Vietnamese đồng','Vietnamese','https://flagcdn.com/w320/vn.png','Asia'),
  ('Jersey','British pound','English','https://flagcdn.com/w320/je.png','Europe'),
  ('Guyana','Guyanese dollar','English','https://flagcdn.com/w320/gy.png','South America'),
  ('Tuvalu','Australian dollar','English','https://flagcdn.com/w320/tv.png','Oceania'),
  ('Jordan','Jordanian dinar','Arabic','https://flagcdn.com/w320/jo.png','Asia'),
  ('Papua New Guinea','Papua New Guinean kina','English','https://flagcdn.com/w320/pg.png','Oceania'),
  ('Bahamas','Bahamian dollar','English','https://flagcdn.com/w320/bs.png','North America'),
  ('Cape Verde','Cape Verdean escudo','Portuguese','https://flagcdn.com/w320/cv.png','Africa'),
  ('Oman','Omani rial','Arabic','https://flagcdn.com/w320/om.png','Asia'),
  ('Venezuela','Venezuelan bolívar soberano','Spanish','https://flagcdn.com/w320/ve.png','South America'),
  ('Egypt','Egyptian pound','Arabic','https://flagcdn.com/w320/eg.png','Africa'),
  ('Bolivia','Bolivian boliviano','Aymara','https://flagcdn.com/w320/bo.png','South America'),
  ('Norway','Norwegian krone','Norwegian Nynorsk','https://flagcdn.com/w320/no.png','Europe'),
  ('Kyrgyzstan','Kyrgyzstani som','Kyrgyz','https://flagcdn.com/w320/kg.png','Asia'),
  ('Canada','Canadian dollar','English','https://flagcdn.com/w320/ca.png','North America'),
  ('Armenia','Armenian dram','Armenian','https://flagcdn.com/w320/am.png','Asia'),
  ('DR Congo','Congolese franc','French','https://flagcdn.com/w320/cd.png','Africa'),
  ('Puerto Rico','United States dollar','English','https://flagcdn.com/w320/pr.png','North America'),
  ('Liechtenstein','Swiss franc','German','https://flagcdn.com/w320/li.png','Europe'),
  ('Eswatini','Swazi lilangeni','English','https://flagcdn.com/w320/sz.png','Africa'),
  ('Faroe Islands','Danish krone','Danish','https://flagcdn.com/w320/fo.png','Europe'),
  ('Nigeria','Nigerian naira','English','https://flagcdn.com/w320/ng.png','Africa'),
  ('Saint Martin','Euro','French','https://flagcdn.com/w320/mf.png','North America'),
  ('Guam','United States dollar','Chamorro','https://flagcdn.com/w320/gu.png','Oceania'),
  ('Malawi','Malawian kwacha','English','https://flagcdn.com/w320/mw.png','Africa'),
  ('Åland Islands','Euro','Swedish','https://flagcdn.com/w320/ax.png','Europe'),
  ('São Tomé and Príncipe','São Tomé and Príncipe dobra','Portuguese','https://flagcdn.com/w320/st.png','Africa'),
  ('Falkland Islands','Falkland Islands pound','English','https://flagcdn.com/w320/fk.png','South America'),
  ('Guatemala','Guatemalan quetzal','Spanish','https://flagcdn.com/w320/gt.png','North America'),
  ('Barbados','Barbadian dollar','English','https://flagcdn.com/w320/bb.png','North America'),
  ('Ghana','Ghanaian cedi','English','https://flagcdn.com/w320/gh.png','Africa'),
  ('Nicaragua','Nicaraguan córdoba','Spanish','https://flagcdn.com/w320/ni.png','North America'),
  ('Isle of Man','British pound','English','https://flagcdn.com/w320/im.png','Europe'),
  ('Portugal','Euro','Portuguese','https://flagcdn.com/w320/pt.png','Europe'),
  ('Angola','Angolan kwanza','Portuguese','https://flagcdn.com/w320/ao.png','Africa'),
  ('Dominican Republic','Dominican peso','Spanish','https://flagcdn.com/w320/do.png','North America'),
  ('Albania','Albanian lek','Albanian','https://flagcdn.com/w320/al.png','Europe'),
  ('Guinea-Bissau','West African CFA franc','Portuguese','https://flagcdn.com/w320/gw.png','Africa'),
  ('Libya','Libyan dinar','Arabic','https://flagcdn.com/w320/ly.png','Africa'),
  ('Kuwait','Kuwaiti dinar','Arabic','https://flagcdn.com/w320/kw.png','Asia'),
  ('Bahrain','Bahraini dinar','Arabic','https://flagcdn.com/w320/bh.png','Asia'),
  ('Turkmenistan','Turkmenistan manat','Russian','https://flagcdn.com/w320/tm.png','Asia'),
  ('Lithuania','Euro','Lithuanian','https://flagcdn.com/w320/lt.png','Europe'),
  ('Tokelau','New Zealand dollar','English','https://flagcdn.com/w320/tk.png','Oceania'),
  ('Latvia','Euro','Latvian','https://flagcdn.com/w320/lv.png','Europe'),
  ('Philippines','Philippine peso','English','https://flagcdn.com/w320/ph.png','Asia'),
  ('New Zealand','New Zealand dollar','English','https://flagcdn.com/w320/nz.png','Oceania'),
  ('Cameroon','Central African CFA franc','English','https://flagcdn.com/w320/cm.png','Africa'),
  ('Ecuador','United States dollar','Spanish','https://flagcdn.com/w320/ec.png','South America'),
  ('Anguilla','Eastern Caribbean dollar','English','https://flagcdn.com/w320/ai.png','North America'),
  ('Romania','Romanian leu','Romanian','https://flagcdn.com/w320/ro.png','Europe'),
  ('India','Indian rupee','English','https://flagcdn.com/w320/in.png','Asia'),
  ('Gabon','Central African CFA franc','French','https://flagcdn.com/w320/ga.png','Africa'),
  ('Russia','Russian ruble','Russian','https://flagcdn.com/w320/ru.png','Europe'),
  ('Myanmar','Burmese kyat','Burmese','https://flagcdn.com/w320/mm.png','Asia'),
  ('Réunion','Euro','French','https://flagcdn.com/w320/re.png','Africa'),
  ('American Samoa','United States dollar','English','https://flagcdn.com/w320/as.png','Oceania'),
  ('Belize','Belize dollar','Belizean Creole','https://flagcdn.com/w320/bz.png','North America'),
  ('Mongolia','Mongolian tögrög','Mongolian','https://flagcdn.com/w320/mn.png','Asia'),
  ('Austria','Euro','German','https://flagcdn.com/w320/at.png','Europe'),
  ('Montserrat','Eastern Caribbean dollar','English','https://flagcdn.com/w320/ms.png','North America'),
  ('Hungary','Hungarian forint','Hungarian','https://flagcdn.com/w320/hu.png','Europe'),
  ('Saudi Arabia','Saudi riyal','Arabic','https://flagcdn.com/w320/sa.png','Asia'),
  ('Montenegro','Euro','Montenegrin','https://flagcdn.com/w320/me.png','Europe'),
  ('Nauru','Australian dollar','English','https://flagcdn.com/w320/nr.png','Oceania'),
  ('Pitcairn Islands','New Zealand dollar','English','https://flagcdn.com/w320/pn.png','Oceania'),
  ('Argentina','Argentine peso','Guaraní','https://flagcdn.com/w320/ar.png','South America'),
  ('Slovakia','Euro','Slovak','https://flagcdn.com/w320/sk.png','Europe'),
  ('Yemen','Yemeni rial','Arabic','https://flagcdn.com/w320/ye.png','Asia'),
  ('Turks and Caicos Islands','United States dollar','English','https://flagcdn.com/w320/tc.png','North America'),
  ('Sweden','Swedish krona','Swedish','https://flagcdn.com/w320/se.png','Europe'),
  ('Italy','Euro','Italian','https://flagcdn.com/w320/it.png','Europe'),
  ('Saint Helena, Ascension and Tristan da Cunha','Pound sterling','English','https://flagcdn.com/w320/sh.png','Africa'),
  ('Wallis and Futuna','CFP franc','French','https://flagcdn.com/w320/wf.png','Oceania'),
  ('Brazil','Brazilian real','Portuguese','https://flagcdn.com/w320/br.png','South America'),
  ('South Sudan','South Sudanese pound','English','https://flagcdn.com/w320/ss.png','Africa'),
  ('Cyprus','Euro','Greek','https://flagcdn.com/w320/cy.png','Europe'),
  ('Turkey','Turkish lira','Turkish','https://flagcdn.com/w320/tr.png','Asia'),
  ('Bermuda','Bermudian dollar','English','https://flagcdn.com/w320/bm.png','North America'),
  ('Australia','Australian dollar','English','https://flagcdn.com/w320/au.png','Oceania'),
  ('Bangladesh','Bangladeshi taka','Bengali','https://flagcdn.com/w320/bd.png','Asia'),
  ('Thailand','Thai baht','Thai','https://flagcdn.com/w320/th.png','Asia'),
  ('Grenada','Eastern Caribbean dollar','English','https://flagcdn.com/w320/gd.png','North America'),
  ('Moldova','Moldovan leu','Romanian','https://flagcdn.com/w320/md.png','Europe'),
  ('Singapore','Singapore dollar','Chinese','https://flagcdn.com/w320/sg.png','Asia'),
  ('Mali','West African CFA franc','French','https://flagcdn.com/w320/ml.png','Africa'),
  ('Kenya','Kenyan shilling','English','https://flagcdn.com/w320/ke.png','Africa'),
  ('Switzerland','Swiss franc','French','https://flagcdn.com/w320/ch.png','Europe'),
  ('Uruguay','Uruguayan peso','Spanish','https://flagcdn.com/w320/uy.png','South America'),
  ('Chad','Central African CFA franc','Arabic','https://flagcdn.com/w320/td.png','Africa'),
  ('Greenland','krone','Greenlandic','https://flagcdn.com/w320/gl.png','North America'),
  ('Belarus','Belarusian ruble','Belarusian','https://flagcdn.com/w320/by.png','Europe'),
  ('Lebanon','Lebanese pound','Arabic','https://flagcdn.com/w320/lb.png','Asia'),
  ('Ivory Coast','West African CFA franc','French','https://flagcdn.com/w320/ci.png','Africa'),
  ('Netherlands','Euro','Dutch','https://flagcdn.com/w320/nl.png','Europe'),
  ('El Salvador','United States dollar','Spanish','https://flagcdn.com/w320/sv.png','North America'),
  ('San Marino','Euro','Italian','https://flagcdn.com/w320/sm.png','Europe'),
  ('Bhutan','Bhutanese ngultrum','Dzongkha','https://flagcdn.com/w320/bt.png','Asia'),
  ('Malaysia','Malaysian ringgit','English','https://flagcdn.com/w320/my.png','Asia'),
  ('Finland','Euro','Finnish','https://flagcdn.com/w320/fi.png','Europe'),
  ('Gambia','dalasi','English','https://flagcdn.com/w320/gm.png','Africa'),
  ('Tunisia','Tunisian dinar','Arabic','https://flagcdn.com/w320/tn.png','Africa'),
  ('Kazakhstan','Kazakhstani tenge','Kazakh','https://flagcdn.com/w320/kz.png','Asia'),
  ('French Southern and Antarctic Lands','Euro','French','https://flagcdn.com/w320/tf.png','Antarctica'),
  ('Syria','Syrian pound','Arabic','https://flagcdn.com/w320/sy.png','Asia'),
  ('Norfolk Island','Australian dollar','English','https://flagcdn.com/w320/nf.png','Oceania'),
  ('Mozambique','Mozambican metical','Portuguese','https://flagcdn.com/w320/mz.png','Africa'),
  ('Caribbean Netherlands','United States dollar','English','https://flagcdn.com/w320/bq.png','North America'),
  ('Samoa','Samoan tālā','English','https://flagcdn.com/w320/ws.png','Oceania'),
  ('Guinea','Guinean franc','French','https://flagcdn.com/w320/gn.png','Africa'),
  ('Taiwan','New Taiwan dollar','Chinese','https://flagcdn.com/w320/tw.png','Asia'),
  ('South Georgia','Saint Helena pound','English','https://flagcdn.com/w320/gs.png','Antarctica'),
  ('North Korea','North Korean won','Korean','https://flagcdn.com/w320/kp.png','Asia'),
  ('Suriname','Surinamese dollar','Dutch','https://flagcdn.com/w320/sr.png','South America'),
  ('Rwanda','Rwandan franc','English','https://flagcdn.com/w320/rw.png','Africa'),
  ('France','Euro','French','https://flagcdn.com/w320/fr.png','Europe'),
  ('Djibouti','Djiboutian franc','Arabic','https://flagcdn.com/w320/dj.png','Africa'),
  ('Curaçao','Netherlands Antillean guilder','English','https://flagcdn.com/w320/cw.png','North America'),
  ('South Korea','South Korean won','Korean','https://flagcdn.com/w320/kr.png','Asia'),
  ('Antarctica','undefined','undefined','https://flagcdn.com/w320/aq.png','Antarctica'),
  ('Slovenia','Euro','Slovene','https://flagcdn.com/w320/si.png','Europe'),
  ('Maldives','Maldivian rufiyaa','Maldivian','https://flagcdn.com/w320/mv.png','Asia'),
  ('Christmas Island','Australian dollar','English','https://flagcdn.com/w320/cx.png','Asia'),
  ('Jamaica','Jamaican dollar','English','https://flagcdn.com/w320/jm.png','North America'),
  ('United States Virgin Islands','United States dollar','English','https://flagcdn.com/w320/vi.png','North America'),
  ('Paraguay','Paraguayan guaraní','Guaraní','https://flagcdn.com/w320/py.png','South America'),
  ('Indonesia','Indonesian rupiah','Indonesian','https://flagcdn.com/w320/id.png','Asia'),
  ('Iraq','Iraqi dinar','Arabic','https://flagcdn.com/w320/iq.png','Asia'),
  ('Morocco','Moroccan dirham','Arabic','https://flagcdn.com/w320/ma.png','Africa'),
  ('Honduras','Honduran lempira','Spanish','https://flagcdn.com/w320/hn.png','North America'),
  ('Madagascar','Malagasy ariary','French','https://flagcdn.com/w320/mg.png','Africa'),
  ('Hong Kong','Hong Kong dollar','English','https://flagcdn.com/w320/hk.png','Asia'),
  ('Antigua and Barbuda','Eastern Caribbean dollar','English','https://flagcdn.com/w320/ag.png','North America'),
  ('Sri Lanka','Sri Lankan rupee','Sinhala','https://flagcdn.com/w320/lk.png','Asia'),
  ('Cuba','Cuban convertible peso','Spanish','https://flagcdn.com/w320/cu.png','North America'),
  ('Cook Islands','Cook Islands dollar','English','https://flagcdn.com/w320/ck.png','Oceania'),
  ('Tajikistan','Tajikistani somoni','Russian','https://flagcdn.com/w320/tj.png','Asia'),
  ('Colombia','Colombian peso','Spanish','https://flagcdn.com/w320/co.png','South America'),
  ('Haiti','Haitian gourde','French','https://flagcdn.com/w320/ht.png','North America'),
  ('Northern Mariana Islands','United States dollar','Carolinian','https://flagcdn.com/w320/mp.png','Oceania'),
  ('Micronesia','United States dollar','English','https://flagcdn.com/w320/fm.png','Oceania'),
  ('Saint Kitts and Nevis','Eastern Caribbean dollar','English','https://flagcdn.com/w320/kn.png','North America'),
  ('Burkina Faso','West African CFA franc','French','https://flagcdn.com/w320/bf.png','Africa'),
  ('Ireland','Euro','English','https://flagcdn.com/w320/ie.png','Europe'),
  ('Peru','Peruvian sol','Aymara','https://flagcdn.com/w320/pe.png','South America'),
  ('Pakistan','Pakistani rupee','English','https://flagcdn.com/w320/pk.png','Asia'),
  ('Gibraltar','Gibraltar pound','English','https://flagcdn.com/w320/gi.png','Europe'),
  ('Zambia','Zambian kwacha','English','https://flagcdn.com/w320/zm.png','Africa'),
  ('Saint Lucia','Eastern Caribbean dollar','English','https://flagcdn.com/w320/lc.png','North America'),
  ('Uzbekistan','Uzbekistani soʻm','Russian','https://flagcdn.com/w320/uz.png','Asia'),
  ('Seychelles','Seychellois rupee','Seychellois Creole','https://flagcdn.com/w320/sc.png','Africa'),
  ('Benin','West African CFA franc','French','https://flagcdn.com/w320/bj.png','Africa'),
  ('United Kingdom','British pound','English','https://flagcdn.com/w320/gb.png','Europe'),
  ('Costa Rica','Costa Rican colón','Spanish','https://flagcdn.com/w320/cr.png','North America'),
  ('Comoros','Comorian franc','Arabic','https://flagcdn.com/w320/km.png','Africa'),
  ('Iceland','Icelandic króna','Icelandic','https://flagcdn.com/w320/is.png','Europe'),
  ('Bouvet Island','undefined','Norwegian','https://flagcdn.com/w320/bv.png','Antarctica'),
  ('Japan','Japanese yen','Japanese','https://flagcdn.com/w320/jp.png','Asia'),
  ('Vatican City','Euro','Italian','https://flagcdn.com/w320/va.png','Europe'),
  ('British Virgin Islands','United States dollar','English','https://flagcdn.com/w320/vg.png','North America'),
  ('Chile','Chilean peso','Spanish','https://flagcdn.com/w320/cl.png','South America'),
  ('Spain','Euro','Spanish','https://flagcdn.com/w320/es.png','Europe'),
  ('Bosnia and Herzegovina','Bosnia and Herzegovina convertible mark','Bosnian','https://flagcdn.com/w320/ba.png','Europe'),
  ('Western Sahara','Algerian dinar','Berber','https://flagcdn.com/w320/eh.png','Africa'),
  ('Mexico','Mexican peso','Spanish','https://flagcdn.com/w320/mx.png','North America'),
  ('Cambodia','Cambodian riel','Khmer','https://flagcdn.com/w320/kh.png','Asia'),
  ('New Caledonia','CFP franc','French','https://flagcdn.com/w320/nc.png','Oceania'),
  ('Saint Vincent and the Grenadines','Eastern Caribbean dollar','English','https://flagcdn.com/w320/vc.png','North America'),
  ('Iran','Iranian rial','Persian (Farsi)','https://flagcdn.com/w320/ir.png','Asia'),
  ('Malta','Euro','English','https://flagcdn.com/w320/mt.png','Europe'),
  ('United Arab Emirates','United Arab Emirates dirham','Arabic','https://flagcdn.com/w320/ae.png','Asia'),
  ('Azerbaijan','Azerbaijani manat','Azerbaijani','https://flagcdn.com/w320/az.png','Asia'),
  ('Heard Island and McDonald Islands','undefined','English','https://flagcdn.com/w320/hm.png','Antarctica'),
  ('French Polynesia','CFP franc','French','https://flagcdn.com/w320/pf.png','Oceania'),
  ('Vanuatu','Vanuatu vatu','Bislama','https://flagcdn.com/w320/vu.png','Oceania'),
  ('Serbia','Serbian dinar','Serbian','https://flagcdn.com/w320/rs.png','Europe'),
  ('Niger','West African CFA franc','French','https://flagcdn.com/w320/ne.png','Africa'),
  ('Eritrea','Eritrean nakfa','Arabic','https://flagcdn.com/w320/er.png','Africa'),
  ('Central African Republic','Central African CFA franc','French','https://flagcdn.com/w320/cf.png','Africa'),
  ('Nepal','Nepalese rupee','Nepali','https://flagcdn.com/w320/np.png','Asia'),
  ('Panama','Panamanian balboa','Spanish','https://flagcdn.com/w320/pa.png','North America'),
  ('Guernsey','British pound','English','https://flagcdn.com/w320/gg.png','Europe'),
  ('Solomon Islands','Solomon Islands dollar','English','https://flagcdn.com/w320/sb.png','Oceania'),
  ('Zimbabwe','Zimbabwean dollar','Chibarwe','https://flagcdn.com/w320/zw.png','Africa'),
  ('Aruba','Aruban florin','Dutch','https://flagcdn.com/w320/aw.png','North America'),
  ('Israel','Israeli new shekel','Arabic','https://flagcdn.com/w320/il.png','Asia'),
  ('Brunei','Brunei dollar','Malay','https://flagcdn.com/w320/bn.png','Asia'),
  ('Denmark','Danish krone','Danish','https://flagcdn.com/w320/dk.png','Europe'),
  ('Belgium','Euro','German','https://flagcdn.com/w320/be.png','Europe'),
  ('Liberia','Liberian dollar','English','https://flagcdn.com/w320/lr.png','Africa'),
  ('Fiji','Fijian dollar','English','https://flagcdn.com/w320/fj.png','Oceania'),
  ('Andorra','Euro','Catalan','https://flagcdn.com/w320/ad.png','Europe'),
  ('Guadeloupe','Euro','French','https://flagcdn.com/w320/gp.png','North America'),
  ('French Guiana','Euro','French','https://flagcdn.com/w320/gf.png','South America'),
  ('Martinique','Euro','French','https://flagcdn.com/w320/mq.png','North America'),
  ('Lesotho','Lesotho loti','English','https://flagcdn.com/w320/ls.png','Africa'),
  ('Dominica','Eastern Caribbean dollar','English','https://flagcdn.com/w320/dm.png','North America'),
  ('Sierra Leone','Sierra Leonean leone','English','https://flagcdn.com/w320/sl.png','Africa'),
  ('Croatia','Euro','Croatian','https://flagcdn.com/w320/hr.png','Europe'),
  ('Saint Barthélemy','Euro','French','https://flagcdn.com/w320/bl.png','North America'),
  ('Somalia','Somali shilling','Arabic','https://flagcdn.com/w320/so.png','Africa'),
  ('Svalbard and Jan Mayen','krone','Norwegian','https://flagcdn.com/w320/sj.png','Europe'),
  ('Saint Pierre and Miquelon','Euro','French','https://flagcdn.com/w320/pm.png','North America'),
  ('United States Minor Outlying Islands','United States dollar','English','https://flagcdn.com/w320/um.png','Oceania'),
  ('Ethiopia','Ethiopian birr','Amharic','https://flagcdn.com/w320/et.png','Africa'),
  ('Senegal','West African CFA franc','French','https://flagcdn.com/w320/sn.png','Africa'),
  ('Luxembourg','Euro','German','https://flagcdn.com/w320/lu.png','Europe'),
  ('China','Chinese yuan','Chinese','https://flagcdn.com/w320/cn.png','Asia'),
  ('Tonga','Tongan paʻanga','English','https://flagcdn.com/w320/to.png','Oceania'),
  ('Cocos (Keeling) Islands','Australian dollar','English','https://flagcdn.com/w320/cc.png','Asia'),
  ('Laos','Lao kip','Lao','https://flagcdn.com/w320/la.png','Asia'),
  ('Burundi','Burundian franc','French','https://flagcdn.com/w320/bi.png','Africa');
